small_app/urls.py

# from django.conf.urls import url
# from django.urls import include, re_path
from django.urls import path
from .views import TaskList ,TaskDetail ,TaskCreate ,TaskUpdate ,TaskDelete ,CustomLoginView , RegisterPage
from django.contrib.auth.views import LogoutView
app_name  = 'small_app'

urlpatterns = [
    path('', TaskList.as_view() , name='tasks'),
    path('<int:pk>/', TaskDetail.as_view() , name='task'),
    path('task-create', TaskCreate.as_view() , name='create'),
    path('update/<int:pk>/', TaskUpdate.as_view() , name='update'),
    path('delete/<int:pk>/', TaskDelete.as_view() , name='delete'),
    path('login', CustomLoginView.as_view() , name='login'),
    path('logout', LogoutView.as_view(next_page='calcs:login') , name='logout'),
    path('register', RegisterPage.as_view() , name='register'),
]

stepOne/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('small_app.urls', namespace='calcs')),
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)






small_app/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# Create your models here.
class Calc (models.Model):
    user = models.ForeignKey(User , on_delete= models.CASCADE , null=True , blank=True)
    title = models.CharField(max_length=200 )
    description = models.TextField(null= True , blank=True)
    created = models.DateTimeField(blank=True , default= datetime.datetime.now)
    completed = models.BooleanField(default=False)
    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['completed']
    

small_app/forms.py
from django import forms
from .models import Calc

# class FormsTemplate(forms.ModelForm):
    
#     class Meta:
#         model = Calc
#         fields = ['Name', 'num1', 'num2', 'total','img']


small_app/views.py
from django.shortcuts import render , redirect
from .models import Calc
from django.contrib.auth.models import User
from django.views.generic.list import  ListView
from django.views.generic.detail import  DetailView
from django.views.generic.edit import  CreateView , UpdateView , DeleteView , FormView
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.urls import reverse_lazy

# Create your views here.

class TaskList(LoginRequiredMixin,ListView):
    model = Calc
    template_name = 'index.html'
    context_object_name = 'tasks'
    def get_context_data(self , **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user = self.request.user)
        context['count'] = context['tasks'].filter(completed = False).count()
        search_input = self.request.GET.get('search') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__startswith=search_input)
            
        context['search_input'] = search_input
        return context

class TaskDetail(LoginRequiredMixin,DetailView):
    model = Calc
    template_name = 'detail.html'
    context_object_name = 'task'


class TaskCreate(LoginRequiredMixin,CreateView):
    model = Calc
    fields = ['title', 'description', 'completed']
    template_name = 'add.html'
    success_url = reverse_lazy('calcs:tasks')
    
    def form_valid(self,form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate (LoginRequiredMixin,UpdateView):
    model = Calc
    template_name = "update.html"
    fields =  ['title', 'description', 'completed']
    success_url = reverse_lazy('calcs:tasks')

class TaskDelete(LoginRequiredMixin,DeleteView):
    model = Calc
    context_object_name = 'task'
    success_url = reverse_lazy('calcs:tasks')
    template_name = 'delete.html'

class RegisterPage(FormView):
    template_name = 'register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('calcs:tasks')
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request , user)
        return super(RegisterPage, self).form_valid(form)
    
    def get(self, *args , **kwargs):
        if self.request.user.is_authenticated:
            return redirect('calcs:tasks')
        return super(RegisterPage, self).get(*args, **kwargs)


class CustomLoginView (LoginView):
    template_name = 'login.html'
    fields = "__all__"
    redirect_authenticated_user = True
    
    def get_success_url(self) -> str:
        return reverse_lazy('calcs:tasks')
    

    
        

small_app/templates/add.html

{% extends 'base.html' %}
{% block body %}

<div class="header-bar">
    <a href='{% url "calcs:tasks" %}'> &#8592; back</a>
</div>
<div class="card-body">
    <form method ='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="button" type='submit'>Add</button>
    </form>
</div>





{% endblock body %}

small_app/templates/base.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TO Do Items</title> 
    <style>
        body{
            background-color: #fafafa;
            padding-top: 50px;
            font-family: Arial, Helvetica;
        }
        .container{
            max-width: 550px;
            margin:auto;
            background-color: #fff;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
            box-shadow: 2px 2px 13px -4px rgba(0,0,0,0.21);
        }
        h1,
        h2,
        h3,
        h4,
        h5,
        h6,
        {
            font-family: 'Raleway', sans-serif;
        }

        a,
        p{
            color: #4b5156 ;
        }
        .header-bar{
            display:flex;
            justify-content:space-between;
            color:#fff;
            padding:10px;
            border-radius: 5px 5px 0 0;
            background: linear-gradient(90deg , #eea390 0% , #eb796f 43%, #eb796f 100%)
        }
        .header-bar a{
            color : rgba(247,247,247);
            text-decoration: none;
        }
        .task-wrapper{
            display:flex;
            align-items:center;
            justify-content:space-between;
            padding:20px;
            background-color: #fff;
            border-top: 1px solid rgb(226,226,226)
        }
        .task-title{
            display:flex;
        }
        .task-title a{
            text-decoration:none;
            color:#4b5156;
            margin-left: 10px;

        }
        .task-complete-icon{
            height:20px;
            width:20px;
            background-color: rgb(105,192,105);
            border-radius: 50%;
        }
        .task-incomplete-icon{
            height:20px;
            width:20px;
            background-color: rgb(218,218,218);
            border-radius: 50%;
        }
        .delete-link{
            text-decoration:none;
            font-weight:900;
            color:#cf4949;
            font-size:22px;
            line-height:0;
        }

        #search-add-wrapper{
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding:10px;
        }
        #search-link{
            color:#eb796f;
            text-decoration:none;
            font-size:42px;
            text-shadow:1px 1px #81413b
        }
        input[type=text],
        input[type=password],
        textarea{
            border:1px solid #eb796f;
            border-radius:5px;
            padding:10px;
            width:90%
        }
        label{
            padding-top:10px !important;
            display : block;
        }
        .button{
            border:1px solid #eb796f;
            background-color:#fafafa;
            color:#eb796f;
            padding:10px;
            font-size:14px;
            border-radius:5px;
            cursor:pointer;
            text-decoration:none;
        }

        .card-body{
            padding:20px;
        }



    </style>   
</head>
<body>

    <div class="container">
        {% block body %}
            
        {% endblock body %}

    </div>

</body>
</html>     

small_app/templates/delete.html

{% extends 'base.html' %}
{% block body %}

<div class="header-bar">
    <a href='{% url "calcs:tasks" %}'> &#8592; back</a>
</div>
<div class="card-body">
    <form method="post">
        {% csrf_token %}
        <P> Are you sure to delete this task ? {{task}}  </p>
        <input class="button" type="submit" value="Delete" />
    </form>
</div>
{% endblock body %}



small_app/templates/detail.html


{% extends 'base.html' %}
{% block body %}

<h1>{{task}}<h1><br>

{% endblock body %}

small_app/templates/index.html
{% extends 'base.html' %}
{% block body %}
    <div class="header-bar">
        <div>
            <h1>Hello {{request.user|title}}</h1>
            <h3 style="margin:0;">You have <i>{{count}} </i>incomplete task{{count|pluralize:"s"}}</h3>
        </div>
        {% if request.user.is_authenticated %}

        <a href="{% url 'calcs:logout' %} "> Logout </a>
        {% else %}
            <a href="{% url 'calcs:login' %}">Login</a>
        {% endif %}
    </div>

    <div id="search-add-wrapper">
        <form method="GET" style="margin-top:20px; display:flex;">
            <input type="text" name="search" value="{{search_input}}" />
            <input  class="button" type="submit" value="search" />
        </form> 
        <a id="search-link" href="{% url 'calcs:create'  %}">&#x2b;</a>
    </div>
    <h1 style="margin: 20px 30px">My TO Do List</h1>
    <div class="task-item-wrapper">
        {% for task in tasks %}
        <div class="task-wrapper">
            {% if task.completed %}
                <div class="task-title">
                    <div class="task-complete-icon"></div>
                    <i><s><a href="{% url 'calcs:update' task.id %}">{{task}}</a></s></i>
                </div>
                <a class="delete-link" href="{% url 'calcs:delete' task.id %}"> &#215; </a>
            {% else %}
                <div class="task-title">
                    <div class="task-incomplete-icon"></div>
                    <a href="{% url 'calcs:update' task.id %}">{{task}}</a>
                </div>
                <a class="delete-link" href="{% url 'calcs:delete' task.id %}"> &#215; </a>
            {% endif %}
            
            
        </div>

        {% empty %}
            <h3 style="margin:30px;padding:20px; color:#eb796f">No items in list</h3>

        {% endfor %}

    </div>



    



{% endblock body %}

small_app/templates/login.html

{% extends 'base.html' %}
{% block body %}
<div class="header-bar">
    <h1>Login</h1>
</div>
<div class="card-body">
    <form method="post">
        {% csrf_token %}
        
        {{form.as_p}}
        <input class="button" type="submit" value="Login" />
        <p>Don't have an account <a href=" {% url 'calcs:register' %}">register</a></p>
    </form>
</div>




{% endblock body %}

small_app/templates/register.html


{% extends 'base.html' %}
{% block body %}
<div class="header-bar">
    <h1>Register</h1>
</div>
<div class="card-body">
    <form method="post">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}
        <label>{{form.password1.label}}</label>
        {{form.password1}}
        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:20px" class="button" type="submit" value="Register" />
        <p>Already have an account <a href="{% url 'calcs:login' %}">Login</a></p>
    </form>
</div>






{%  endblock body%}

small_app/templates/update.html

{% extends 'base.html' %}
{% block body %}



<div class="header-bar">
    <a href='{% url "calcs:tasks" %}'> &#8592; back</a>
</div>
<div class="card-body">
    <form method ='post' enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button class="button" type='submit'>Update</button>
    </form>
</div>

{% endblock body %}